### ISSUE TITLE
Support remote supplemental content

### ISSUE THREAD

**Issue by breakid** [OpenDSA/OpenDSA#165]
Ideally, we would like to support linking to AVs, Exercises, etc on a remote system (for example, hosting their own module files, but linking to http://algoviz.org/OpenDSA/AV/ for their AV files)

* In avembed.py, check whether specified av_path is local or remote
** If its remote, use that path
** If its local, use type to determine whether to use 'av_dir' or 'exercise_dir' as the prefix for av_path.  If 'av_dir' or 'exercise_dir' is a remote path, use it as a prefix otherwise if its local calculate the appropriate relative path

Problems:
* The avembed directive reads XML files from within the specified directory which poses a problem for remotely hosted files 
** One solution would be to include the 'height' and 'width' properties in the config file (which would make sense anyway)
* If remote files we used, we will likely run into a problem with 3rd party cookies

**Comment by cashaffer** [comment]
Not sure if this is still relevant. If we get a use case for this that breaks, then we can raise the issue again. Closing.
