### ISSUE TITLE
Registration through Aalto

### ISSUE THREAD

**Issue by breakid** [OpenDSA/OpenDSA#170]
* Create an Aalto registration page that allows users to create a new account
* Create a course management page that lets users to view their current courses and enroll in new ones
* Selecting a course will display links to the course book(s) (link to associated OpenDSA textbook)
* Investigate possibility of using cross-domain localStorage to allow a user's Aalto session to be used for OpenDSA as well preventing the user from having to log in again
  * XAuth - http://www.nczonline.net/blog/2010/09/07/learning-from-xauth-cross-domain-localstorage/
* Remove the registration code from OpenDSA, set the register link to open the Aalto registration page

**Comment by cashaffer** [comment]
With the new LTI infrastructure, this should be obsolete. Closing.
