### ISSUE TITLE
Presentation support

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#182]
A useful feature would be a presentation mode, something functionally equivalent to powerpoint slides for use in lecture. Using modules as a lecture aide is helpful but limited, in that it allows presentation of AVs, slideshows, and exercises, but its not really designed for lecture presentation. An easy way to break a presentation into "slides" would be helpful. We don't really want to use JSAV slideshows for making coursenotes (reST is far easier for creating text layout). But we don't want a separate RST file for each slide.

**Comment by bedmison** [comment]
Slide generation is supported now.
