### ISSUE TITLE
Should speed up js files loading in new Khan framework.

### ISSUE THREAD

**Issue by junyangchen** [OpenDSA/OpenDSA#202]
Since we run khan-exercise in localMode, scripts that have dependencies order will be loaded one after another, which reduces the performance greatly.

One solution for this could be to minify and combine js files and load the combined files at the end of the page.

http://www.1stwebdesigner.com/design/load-javascript-faster/

**Comment by cashaffer** [comment]
I hope that with the new Khan Academy infrastructure using require.js, along with all of the other changes made over the years, that this is no longer a significant issue. Closing.
