### ISSUE TITLE
:prerequisites: tag in avmetadata directive is obsolete and should be removed.

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#233]
This functionality has been replaced by the :requires: and :satisfies: tags.

**Comment by cashaffer** [comment]
Passing this to Cory. Hopefully this is trivial for you. Just purge the directive, and I will fix any remaining modules that it breaks.

**Comment by acbart** [comment]
Something like this? 7a202a34deb84380cdfa12ae0c4a39182849a015

**Comment by cashaffer** [comment]
I guess so. I took a look at where this stuff is processed. There does not seem to be any code in ODSA_RST_Module.py that handle the "prerequisites" field, just the "requires" field (which is what we want). So hopefully what you did is all that we need. Thanks!

**Comment by cashaffer** [comment]
Where is "index.rst" created? I am assuming that is part of the compilation process. Something is creating "index.rst" with a "prerequisites" tag.

**Comment by cashaffer** [comment]
Found it. I think that we are good now.
