### ISSUE TITLE
Implement iFrame resizing for KA exercises

### ISSUE THREAD

**Issue by breakid** [OpenDSA/OpenDSA#255]
Refer to sendResizeMsg() in odsaAV.js.  Note that the function is called with a 100 millisecond timeout after the DOM has been loaded to ensure the page has finished rendering, i.e.:

$(document).ready(function () {
  setTimeout(function () {sendResizeMsg()}, 100);
});

The way the height and width are calculated will have to be changed since the current version relies on standard containers we use on all AV exercises. 

I don't expect any changes to odsaMOD.js would have to be made.

Note that some changes must be made to accommodate postMessage for local testing.  These changes are explained in comments in odsaAV.js and odsaMOD.js and marked with the word "IMPORTANT".

After implementing iFrame resizing for KA exercises, the avembed RST directive can be changed to eliminate our dependence on the oEmbed XML files.

**Comment by cashaffer** [comment]
This has been in place for awhile now. Seems to work great. Closing.
