### ISSUE TITLE
Exercise controls too far away from the canvas

### ISSUE THREAD

**Issue by X455u** [OpenDSA/OpenDSA#258]
The OpenDSA layout for the proficiency exercises puts the jsav control buttons on the top of the AV. This can be quite troubling in case the user has a small screen and the exercise contains several rows of code.

Example:
![screen shot 2014-10-01 at 13 57 53](https://cloud.githubusercontent.com/assets/3896558/4473988/ffea645a-4959-11e4-836f-fc615e94ca02.png)

http://algoviz.org/OpenDSA/dev/OpenDSA/AV/Sorting/heapsortPRO.html?JXOP-code=pseudo&JXOP-feedback=atend

**Comment by bedmison** [comment]
Can we close this? Example URL is dead, and screen size isn't really an issue now.
