### ISSUE TITLE
MathJax in KA exercises does not display properly

### ISSUE THREAD

**Issue by breakid** [OpenDSA/OpenDSA#269]
MathJax content in KA exercises occasionally does not load properly as seen in the attached image.  I have only observed this behavior when the exercises are embedded in a module page.

![selection_002](https://cloud.githubusercontent.com/assets/1446918/4800773/8b21c994-5e29-11e4-9649-3362edb66ddf.png)

**Comment by cashaffer** [comment]
So far as I know, this does not happen anymore. Closing for now.
