### ISSUE TITLE
Huffman coding tree visualization example reports an incorrect code

### ISSUE THREAD

**Issue by DaveParillo** [OpenDSA/OpenDSA#274]
On the OpenDSA example site, http://algoviz.org/OpenDSA/dev/OpenDSA/AV/Binary/huffmanBuildAV.html, the text for Step 35 indicates:
> Huffman code for character "D" is: "00", which is the value which is the value along the path from the root "274" to "42"

This path leads to "L", not "D".  The code for "D" should be "101".  I didn't see anything obviously wrong in OpenDSA,  so it's the possible the issue is actually in JSAV, not sure though, so I'm just capturing it here.  

Suspect the root cause of the problem is that both of these nodes have the same frequency count.

**Comment by cashaffer** [comment]
Good catch! You were right, the problem is that the huffman tree's findNode search function was looking for a frequency, not a letter value. I have fixed it and pushed the change onto the server. Thanks!
