### ISSUE TITLE
dispModComp option does not work for logged in users

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#276]
The "dispModComp" option for a module is meant to cause a "Module Complete" label to appear when the user views a module that has no exercises. And so this should get remembered and displayed appropriately in the gradebook as well.

An anonymous user who opens a module with this tag will see the "Module Complete" message as appropriate.

A user who has logged in does not see the "Module Complete" message on modules that have been tagged with the "dispModComp" option.

I am guessing that the cause is that the server-side database does not actually track this information. That it is only localstorage that knows about this. Since we fixed the progress information to only be generated from what the server is telling us for a logged in user, this therefore is not getting transmitted.

**Comment by efouh** [comment]
Should be fixed now. https://github.com/OpenDSA/OpenDSA-server/commit/9538f6f5459d915fa560effbda51931c34dae132

**Comment by cashaffer** [comment]
Closing.
