### ISSUE TITLE
Slashes for null pointers in linked lists

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#280]
The OpenDSA standard for linked lists is to put a slash in the pointer box for null pointers (the end of the list for singly linked lists, and both the start and end of the list for doubly linked lists). Either as a change to the base definition in JSAV for linked lists or as an extension, this should be supported automatically. Right now, all AVs with linked lists are dealing with this more-or-less manually (there exist some less-than-perfect convenience functions for adding the slashes).

**Comment by vkaravir** [comment]
Is this a JSAV issue or an OpenDSA issue? I think this could be implemented as the default visualisation for null pointers in linked lists in JSAV.

**Comment by cashaffer** [comment]
I would like it to be a JSAV issue. :) I debated which issue tracker to put this in... If you are willing for this to be the default visualization, I would appreciate it. I suppose that actually getting it implemented is another issue. :) Junyang did a rather imperfect implementation with the "addTail" method currently at AV/List/llistCON.js. It is unreliable in its placement.

**Comment by vkaravir** [comment]
I decided that this is a JSAV issue :) I implemented this in JSAV and cleaned the AVs. Feel free to merge the pull request if I didn't break anything.

**Comment by cashaffer** [comment]
Merged. Closing.
