### ISSUE TITLE
LTI postprocessing script doesn't generate html files when exercises object is empty

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA#281]
It seems when the module doesn't have any exercises the script will not generate any html files. For example look at "AlgAnal/AnalAsymptotic" module in CS3114 book.

**Comment by acbart** [comment]
Fixed by 209ee4109835814b8288ed8b9d36933f9f094d15, I believe. Neglected to consider the case of "no exercises".

**Comment by hosamshahin** [comment]
Thanks, but we need to fix href="_images/plot.png" as well

**Comment by cashaffer** [comment]
Looks to be resolved. Closing.
