### ISSUE TITLE
New KA: Support hierarchical summary exercises

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#286]
Hosam's mechanism for processing summary exercises essentially replaces the summary references with the the contents of the referenced exercise. This only works to one level. We need to support at least two levels. Could be hacked for two levels, or could be done recursively.

**Comment by hosamshahin** [comment]
For example AlgAnalSumm.html loads inner summary exercises recursively. Still have doubt how data-weight in the below inner summary will affect the individual exercises inside AnalPrelimSumm
<div class="exercise" data-name="AnalPrelimSumm" data-weight="13"></div>

**Comment by cashaffer** [comment]
I think we have some problems. I played around with AlgAnalSumm (and AlgAnalCS2114Summ). I fixed them to reference the new name for GrowthRatesPRO. Generally, it works. But:
1) The weighting is clearly broken. I set GrowthRatesPRO's weight to 400. What happened is that some other exercise "locked" such that the same instance of that exercise kept repeating.
2) No matter what I did, I couldn't make an instance of GrowthRatesPRO come up. I tried upping the weight (see (1)), and then I tried chopping out a bunch of other exercises. If there are any options, this one won't show. If I removed EVERYTHING except that, then it works OK.

Also, sometimes when loading, I get a timeout error. It seems to take a long time to process.

**Comment by hosamshahin** [comment]
Here below AlgAnalSumm.html. As of now all weights assigned to inner summary exercises (like AnalPrelimSumm) are discarded, meaning all individual exercises in AnalPrelimSumm (and other summaries) will have equal weight of 1. The question is what does it mean to have weight of 13 assigned to AnalPrelimSumm summary exercise? I realized that the weight corresponds to the number of questions in each summary exercise. But what does it mean in terms of probability for each individual to show up?

`<!DOCTYPE html>
<html data-require="math">
  <head>
    <title>Algorithm Analysis Summary Questions</title>
    <script src="//cdnjs.cloudflare.com/ajax/libs/require.js/2.1.14/require.min.js"></script>
    <script src="../../khan-exercises/local-only/main.js" ></script>
  </head>

  <body data-height="880" data-width="950">
    <div class="exercise" data-name="AnalPrelimSumm" data-weight="13"></div>
    <div class="exercise" data-name="CompareAlgSumm" data-weight="6"></div>
    <div class="exercise" data-name="GrowthRatesPRO" data-weight="4"></div>
    <div class="exercise" data-name="FasterCorASumm" data-weight="4"></div>
    <div class="exercise" data-name="UpperBoundsSumm" data-weight="6"></div>
    <div class="exercise" data-name="LowerThetaSumm" data-weight="16"></div>
    <div class="exercise" data-name="AnalProgramSumm" data-weight="9"></div>
    <div class="exercise" data-name="AnalProblemSumm" data-weight="9"></div>
    <div class="exercise" data-name="MisSumm" data-weight="6"></div>
  </body>
</html>
`

**Comment by cashaffer** [comment]
Actually, I think that best practice is NOT to weight the summaries by number of questions in your expansion approach, because more questions effectively translates to more opportunities (meaning more weight). Where we need the weight is for something like GrowthRatesPRO. This is a single exercise with variations. Absent any weighting, it will only show up as often as some static TF question.

So the simple solution would be not to weight actually summaries, and usually only weight parameterized "single" questions. And the weight should just filter down. So if I give GrowthRatesPRO a weight of 6, that means it should get that weight when copied into the bottom level, effectively making it appear 6 times as often as an individual, static question.

**Comment by hosamshahin** [comment]
This is exactly the current behavior. Only weights assigned to inner summary exercises will be discarded while weights of individual exercises are copied.

**Comment by cashaffer** [comment]
I still have this problem, referenced above. I can't make GrowthRatesPRO come up in the AlgAnalSumm exercise.

2) No matter what I did, I couldn't make an instance of GrowthRatesPRO come up. I tried upping the weight (see (1)), and then I tried chopping out a bunch of other exercises. If there are any options, this one won't show. If I removed EVERYTHING except that, then it works OK.

**Comment by hosamshahin** [comment]
I don't know why this is happening, I can see that all inner summaries and GrothRatesPRO are loaded with the correct weights. I know that by making a break point in https://github.com/OpenDSA/khan-exercises/blob/master/khan-exercise.js#L1074 and check typeIndex array which indicate how many times one exercise should show up. 

May be this issue related to the 10 questions limit issue Kyu is investigating? I don't know.

**Comment by hosamshahin** [comment]
I found the issue and it should be working find now.
