### ISSUE TITLE
Increase width of new KA exercises

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#290]
[I know that Hosam is already working on this, but wanted to document it and give some details.]

With our new implementation with the KA exercise framework, the actual working area for the JSAV canvas appears to be 475 pixels. This is rather constraining. Any increase will help (even 500px would make a difference). But 600px would be greatly appreciated! We probably get diminishing returns after that. Ideally, we would make the width the same as what we are using for the slideshows.

**Comment by cashaffer** [comment]
(On the NewKA branch): When I look at an exercise directly, it is wider. But when I look at an exercise within a book, it seems t be the old width.

**Comment by hosamshahin** [comment]
The width will change with JSAV exercises only (when data-require tag has jsav)

**Comment by cashaffer** [comment]
OK, it seems to be working as you indicate. But I don't see any advantage to making the width be different for the JSAV vs. non-JSAV exercises. Might as well make them all the wider size, given that it will still be less than the minimum page width dictated by the rest of the system.

**Comment by hosamshahin** [comment]
Now all KA exercises will have 850px width.
