### ISSUE TITLE
Feedback to the student in the programming exercises

### ISSUE THREAD

**Issue by sallyhamouda** [OpenDSA/OpenDSA#292]
In the programming exercises, the format of the feedback that appears to the student in case of an incorrect answer should be different from the hints format. We may have the feedback  with a different color  or with a different background color. We may have it with the same format but in a separate window.

**Comment by hosamshahin** [comment]
@cashaffer @sallyhamouda 
I've created a non-blocking dialog that will open when server sends error feedback to student. The Dialog is dragable and resizable and student can close it when he is done.

Please check and let me know

**Comment by cashaffer** [comment]
Looks like this works well. Closing.
