### ISSUE TITLE
Feedback within Canvas

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#293]
When a student is working on materials within Canvas, we want the following feedbacks about what has been completed:
1) On the Modules page, some sort of check mark or shading for each item that is completed.
2) On the modules page, "assignment" items have an entry in the points column that now reads "# pts". That should be something like "#/# pts".
3) Items that have no exercises (as defined by the config file) should automatically be listed as a 0 point "assignment".
4) On the Assignments page, some visual indication for which items have been completed (besides the current #/# pts)
5) On the Grades page, all items should be listed (this should get satisfied by doing (3)).
6) On the Grades page, the bottom two lines (Assignments and Total) are meaningless and should be removed.

**Comment by hosamshahin** [comment]
3) Items that have no exercises (as defined by the config file) should automatically be listed as a 0 point "assignment".
Done

**Comment by cashaffer** [comment]
I see that the "Intro" module shows up on the Grades and Assignments pages as a 0 pt exercise. When I go to the page, it shows "Module Complete" (but only if I explicitly put dispModComp:true as a field for that module in the config file). Nothing seems to make the Grades page show the module as having been done. It does not list 0 pts in the score field or highlight the line. Likewise in the Assignments page.
