### ISSUE TITLE
Canvas scrollbar-within-a-scrollbar problem

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#294]
Per our discussion today, all "item" pages should include JavaScript to automatically resize the iframe within the Canvas page so that we have only one scrollbar.

**Comment by hosamshahin** [comment]
Should work fine now.

**Comment by cashaffer** [comment]
I have recompiled, and I am looking at a Canvas instance of the CS3114_rev course. The results are a bit hit or miss.

Intro: Has about a one inch blank at the bottom.
Binary Search Tree Definition has nearly an entire screen height blank at the bottom.
BST Search has about 2 inches.
BST Search Exercise has an internal scroll bar, and about half an inch or so gap additional gap.
BST Insert has about an inch at the bottom.
BST Insert Exercise again has an internal scroll bar, and half an inch gap.
And so on.

**Comment by cashaffer** [comment]
This appears to be working pretty well now. There are some gaps at the bottom of some pages. Mostly this might be because Canvas appears to have a minimum iframe height. There are a couple of cases yet where there are large, unexplained gaps at the bottom of the page. I'll open a specific issue next time this comes up. Closing this one.
