### ISSUE TITLE
CSS files in lti-html pages

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#295]
Per our earlier discussions, I know that Cory has already started working on this. So far as I can tell, this is now resolved? I just re-created CS3114_rev, and the BST search slideshow appears to be laid out correctly.

I did not see any problems, which Hosam's email addressed. Can I assume that Cory then resolved it?

Can we say that this issue is closed?

Also, it seems like it should be a quick fix at the same place in the code to fix #285.

**Comment by acbart** [comment]
Yep should be fixed now!
