### ISSUE TITLE
Providing access to sample OpenDSA book instances

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#299]
We need to provide public access to various sample book instances. If the model for access is via Canvas, presumably at the public site canvas.instructure.com, then we will need to support one more more of the following use cases:
1) User follows a URL that we post that lets them view "modules" in a "public" book with no login. Not sure that this is supported. Downside is that they probably cannot work exercises without logging in.
2) User follows a URL, and we give them info for logging in to a "guest" account at the site. This would be a pre-enrolled account that permits viewing and working exercises. Downside is that the account has only one state, so it will probably "look like" the various exercises have already been done.
3) User can log in (perhaps after creating an account) at the site, and go to the course. Downside is that the site has to support "self enrollment" into the course (hopefully this can be arranged, I think that their "public MOOC" courses work this way). Another downside is that users often resist creating accounts (which is why we would want to supply the "guest account" mechanism from (2)). Upside is that the user can then work exercises (and store scores).

**Comment by acbart** [comment]
Might be relevant: http://guides.instructure.com/m/4152/l/48290-how-do-i-change-self-enrollment-settings-for-my-course

**Comment by cashaffer** [comment]
Unfortunately, this is not much help. I already know that people can self-enroll, such as at the public Instructure site. The real issue is that when we update a course (with the present process), the URL changes. So we currently have no reliable way to give out a URL.

**Comment by cashaffer** [comment]
Since our URLs are now reasonably stable, we can close this for now.
