### ISSUE TITLE
Canvas course internal cross links

### ISSUE THREAD

**Issue by hosamshahin** [OpenDSA/OpenDSA#307]
@acbart, 

   I've changed the course creation mechanism to save all Ids returned from canvas into the 
config object.
You can find 'course_id' defined at the top level of the object and in each section there is 'item_id' which is the Id of that section in canvas, in case of OpenDSA module doesn't have any sections (like 'Intro') the 'item_id' will be in module level.

Notice that canvas links follow this format 
https://canvas.instructure.com/courses/<\<course_id\>>/modules/items/<\<item_id\>>. So with the updated config object we can update internal links to match canvas format.

Let me know if you need more information.

**Comment by cashaffer** [comment]
This relates to #301

**Comment by acbart** [comment]
What should happen if users run without the --create_course flag being set? Does it just generate the old fashioned links?

**Comment by acbart** [comment]
Previously, OpenDSA mapped to a module ("QueueLinked.html"), not to a section ("QueueLinked-03.html"). How should this be accounted for; do we just redirect to the start of the module? I assume that no pages do an internal link across pages ("QueueLinked.html#Linked-Enqueue")?

**Comment by acbart** [comment]
Finally, could someone give me an example of one of these internal links, since I couldn't find one searching quickly.

**Comment by cashaffer** [comment]
(1) I do not know about --create_course flag. All I see is what is in the Makefile: Either I include "-c True" (and then it runs Hosam's stuff to push to Canvas), or I do not (then it only runs local compilation). I am not sure that it should make any difference to what you do.

(2) There are three types of links that I can think of. One is glossary links. Of course we want to go directly to that point on the glossary page for the glossary entry. Next is module references. It is fine to go the the first "page" of the module. The third type of link is to (for example) a figure. Which should go to that place on the appropriate (section) page.

(3) Module Sorting/InSort.rst has :ref: links that go to modules (actually, they will default to glossary entries if there is no corresponding module in this particular book instance).

Background/Proofs.rst has several :num: directives to reference (local -- as in, the same module) figures, tables, and examples. You can grep for ":num:" to find other references.

At the moment, I haven't come across an example of a figure or table reference to an artifact in another module. However, I expect that some of the :num: directives in existing modules will point to artifacts in other sections (within the same module).

**Comment by acbart** [comment]
So wait, linking to a figure can happen across Canvas Assignments? That is, a figure on "QueueLinked-03.html" is supposed to link to "Proofs-07.html"? Because that may be an extremely challenging endpoint to resolve.

**Comment by cashaffer** [comment]
I thought that Hosam already had that stuff set up. You have a structure for the book created early, so that things can be pushed to Canvas. If that structure does not capture labels, perhaps it could.

In any case, start with the within-module links and links to the glossary.

**Comment by cashaffer** [comment]
Bringing Kyu into this discussion.

**Comment by hosamshahin** [comment]
Links to Glossary page are working correctly now, also references to modules will direct the user to the first section in the module. I've also fixed the broken back button problem in Glossary page.

**Comment by cashaffer** [comment]
This looks to be working correctly, thanks! Closing.
