### ISSUE TITLE
Bug when pushing biography modules to Canvas

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#312]
The "biography" modules in the "Everything" book compile locally, but something breaks when they get pushed to Canvas. It throws warning messages. Then in Canvas, the chapter header appears on the module list, but the modules themselves don't show up. I am going to guess that it might be "sidebar" directive causing the problem.

**Comment by cashaffer** [comment]
It is not "sidebar". For example, the IntroUML module uses this extensively.

I created a config file named "Test.json" that demonstrates another problematic module: IntroProcess.

**Comment by DaveParillo** [comment]
Sorry - did not intend for my atypical formatting to cause migration issues!

**Comment by cashaffer** [comment]
Don't be sorry. :) These are good tests for a lot of visual elements that we have not used much before.

**Comment by cashaffer** [comment]
Looks like all of these problems were caused by me leaving the "long_name" field out when I added them to the configuration file. An appropriate warning message should resolve the issue.

**Comment by cashaffer** [comment]
I just checked, and at this time (for at least some modules), it no longer crashes if there is a missing "long_name". But there is no warning, either. Some better validation of the config file would help. I think that is already in Hosam's plans, and this is an instance of the issue.

**Comment by cashaffer** [comment]
I think that this issue is obsolete, both due to validation improvements and changes to configuration.
