### ISSUE TITLE
Audit logging of KA exercise clickstream

### ISSUE THREAD

**Issue by cashaffer** [OpenDSA/OpenDSA#325]
We need to confirm that we are collecting the entire clickstream that goes on inside a Khan Academy exercise. Hosam is concerned that we do not, for example, collect all of the wrong choices that a student might make when answering a given MCQ, because the KA framework might not report the actions to the server.

Either confirm that we are indeed collecting everything, or update the framework to do the logging properly.

**Comment by hosamshahin** [comment]
I've double checked and found that our customization to the new KA framework sends every attempt to the server. So I confirm that all correct and incorrect attempts are collected by the server.

**Comment by cashaffer** [comment]
Thanks! Done then.
