### ISSUE TITLE
Problems with book compilation.

### ISSUE THREAD

**Issue by taylorr7** [OpenDSA/OpenDSA#329]
Just a list of the issues with the book compilation process that I am working on fixing:

- Links to the glossary page do not always work.
- Links to other modules do not always work.
- Compilation errors are vague and need to be reworked.
- Web application needs to provide additional feedback to the user during compilation process.

If there is anything that I missed, let me know. I'll continue to add things to this list as they come up.

**Comment by cashaffer** [comment]
So far as I know, these issues have been dealt with over the past year. Will post specific issues for any that pop up at this point.
