### ISSUE TITLE
Erratum in 8.8.1.3. Analyzing Binary Search

### ISSUE THREAD

**Issue by PeterDrake** [OpenDSA/OpenDSA#336]
At the top of the animation, the summation is from 0 to log n. In the diagram below, though, the summation is shown as going from 1 to n. This occurs in slides 7 and 8 of the animation.

**Comment by cashaffer** [comment]
Thanks for pointing this out! Looks like Mohammed has already fixed this. It might take some time to propagate to various textbook instances.
