### ISSUE TITLE
Minor typo in Prim's Priority Queue Visualization (extra I in "Prioirity")

### ISSUE THREAD

**Issue by acbart** [OpenDSA/OpenDSA#341]
https://github.com/OpenDSA/OpenDSA/blob/872bca3c14c78bfdffb44575520c9287cef9c1f8/AV/Graph/PrimAVPQ.html#L19

Just a minor typo, I assume this is the usual way to report such things?

**Comment by cashaffer** [comment]
Thanks! I fixed this in the source. It will take time to roll out onto the production server or into compiled products.

I guess this would be a good way to report. :) Or email to me.
