### ISSUE TITLE
Missing minor step in Moodle Course Creation guide

### ISSUE THREAD

**Issue by acbart** [OpenDSA/OpenDSA#348]
There's a very minor step missing in the guide for adding OpenDSA as an LTI tool in Moodle. I tried looking for the source myself to make a more concrete pull request, but for some reason I cannot find where this [page](https://opendsa-server.cs.vt.edu/guides/opendsa-moodle) came from.

Basically, the instructions don't mention you should add a Tool Name. It's obvious in retrospect (it even shows up in the images), but I was following the guide without thinking. I'd say a quick sentence in Step 7 might be helpful. Stylistically, it also seems like there should be a series of bullets since there's a list of at least 3 steps already in Step 7; I almost missed the bit about tool URL because I was skimming.

**Comment by jwonderly** [comment]
The files for the guides are kept in the OpenDSA-LTI repository: https://github.com/OpenDSA/OpenDSA-LTI/tree/master/app/views/guides

I have updated the guide according to your feedback.
