### ISSUE TITLE
Obscure sentence in `Design/ADT`

### ISSUE THREAD

**Issue by Lemmingh** [OpenDSA/OpenDSA#501]
<https://github.com/OpenDSA/OpenDSA/blob/2e6c42de23148c8c681fde079eb22ea35cec444e/RST/en/Design/ADT.rst#L142-L145>

### Problem

It took me about 10 minutes to segment and grasp this piece:

> (❌) One application that makes use of some ADT might use particular member functions of that ADT more than a second / application
>
> (❌) One application that makes use of some ADT might use particular member functions of that ADT / more than a second application
>
> (❌) One application that makes use of some ADT / might use particular member functions of that ADT / more than a second application
>
> (❌) One application that makes use of some ADT / might use / particular member functions of that ADT / more than / a second application
>
> (❌) One application / that makes use of some ADT / might use / particular member functions of that ADT / more than / a second application
>
> (✔) One application / that makes use of some ADT / might use / particular member functions of that ADT / more / than / a second application
>
> (✔) One application / that makes use of some ADT / might use particular member functions of that ADT / more / than a second application

### Suggestion

Please simplify the expression. For example:

> For two applications that make use of an ADT, one might use particular operations more frequently than the other, or they might have different time requirements for the various operations.

**Comment by cashaffer** [comment]
Thank you for the suggestion! I have reworded that paragraph in a way close to what you recommend.
