### ISSUE TITLE
BST insertion inconsistency in textbook

### ISSUE THREAD

**Issue by sublime09** [OpenDSA/OpenDSA#585]
See https://github.com/OpenDSA/OpenDSA/blob/1b7b33ddcbe7000f27568fa72e305759e8653826/RST/en/Binary/BST.rst#binary-search-tree-definition 

The AV/Binary/BSTShapeCON.js diagram shows BSTs with duplicate 42 inserted.  And two orderings of insertion.  Focus on the (a) ordering. 
![image](https://github.com/OpenDSA/OpenDSA/assets/23484737/a75101e4-b5d8-40d1-abe0-3a83d3ef504e)

While the BST is valid, it doesn't match up with the insert process shown further down on the same page.  
![image](https://github.com/OpenDSA/OpenDSA/assets/23484737/4a440de1-9276-4349-a3d1-9892cb438061)

Something more complex is happening.  Changing the insertion order for (a) from 
`37, 24, 42, 7, 2, 40, 42, 32, 120`   to 
`37, 24, 42, 7, 2, 42, 40, 32, 120`    would solve this I think.

**Comment by cashaffer** [comment]
You are right! I just pushed the change to the figure caption for the correct insert ordering (that is easier than changing the diagram).
