### ISSUE TITLE
Student reports stray node in vis

### ISSUE THREAD

**Issue by bedmison** [OpenDSA/OpenDSA#592]
Found in Spring 24 CS 3114’s Open DSA in section 13.03. Link: [https://canvas.vt.edu/courses/190133/assignments/1965103?module_item_id=2703437](https://canvas.vt.edu/courses/190133/assignments/1965103?module_item_id=2703437) 

<img width="1059" alt="Screen Shot 2024-05-02 at 16 54 46" src="https://github.com/OpenDSA/OpenDSA/assets/3663768/34841e93-82d3-40ec-88f0-8705caa309f9">

**Comment by cashaffer** [comment]
Should be fixed now.
