### ISSUE TITLE
"Lower Bounds For Sorting" Visualization is Missing

### ISSUE THREAD

**Issue by spragunr** [OpenDSA/OpenDSA#625]
In my Canvas course this page is missing the visualization and exercises.  The same issue seems to exist in the public reference version of OpenDSA:

https://opendsa-server.cs.vt.edu/ODSA/Books/Everything/html/SortingLowerBound.html

I've tried accessing the page in both Firefox and Chrome.

**Comment by bedmison** [comment]
The console is showing a 404 error for the reference to the visualization:

https://opendsa-server.cs.vt.edu/ODSA/Books/Everything/html/SortingLowerBoundCON.json

The in-file URL ref is 
`<script type="text/javascript"src="../../../AV/Sorting/SortingLowerBoundCON.js"></script>`

**Comment by cashaffer** [comment]
I started looking into this. The issue appears to be that odsaUtils has to figure out the path to the supporting JSON file. In this case, it got it wrong. But so far, I cannot figure out any reason why sometimes its working and sometimes its not.

Note for example that the page Nathan reports is:
[https://opendsa-server.cs.vt.edu/ODSA/Books/Everything/html/SortingLowerBound.html](https://opendsa-server.cs.vt.edu/ODSA/Books/Everything/html/SortingLowerBound.html).

But this page, compiled in the same way at the same time, works.
[https://opendsa-server.cs.vt.edu/ODSA/Books/CS3/html/SortingLowerBound.html](https://opendsa-server.cs.vt.edu/ODSA/Books/CS3/html/SortingLowerBound.html)

**Comment by spragunr** [comment]
Note that I was able to work around this by importing the page from a colleague's course, where it is working correctly.

**Comment by cashaffer** [comment]
Closing, since hopefully this is resolved.
